# data config
data_path: data/train.txt
train_percent: 0.8
# model config
block_size: 256
vocab_size: 7587
n_layer: 26
n_head: 15
n_embd: 960
dropout: 0.05
bias: True
compile: True
# training config
max_epoch : 1919810
tensorboard_path :  ./tensorboard
device: cuda
eval_freq: 500
eval_steps: 1000
train_batch: 24
test_batch: 8
grad_clip: 1.0
# learning rate
lr : 2e-4
warmup_steps: 1000
decay_steps: 100000
min_lr: 1e-5


# AdamW optimizer
weight_decay : 1e-1
beta1: 0.9
beta2: 0.95
# checkpoint config
checkpoint_root: ./checkpoints
save_freq: 4000 # save when global_step % save_freq == 0
resume_from: NULL
# other config
seed :  114514